"""empty message

Revision ID: 4f8621718424
Revises: 
Create Date: 2019-12-27 14:15:29.454467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8621718424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('customer_class', sa.Enum('Enduser', 'Reseller', 'ResellerHighVolume'), nullable=True),
    sa.Column('vat_percentage', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Deleted'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_net', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('price_gross', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price_net', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
